services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: simpleflashcard-prod
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
    volumes:
      - ./app/db.db:/app/db.db
    restart: unless-stopped
